USE ngo_db;

INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (1, '572 Clove Way', 'Roxbury', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (2, '54 Derek Lane', 'Allston', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (3, '49511 Hanson Alley', 'South End', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (4, '6918 Burning Wood Plaza', 'Back Bay', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (5, '9480 Fairfield Junction', 'Back Bay', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (6, '292 Bellgrove Hill', 'Allston', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (7, '81 Mayer Junction', 'Roxbury', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (8, '3070 Sherman Circle', 'Roxbury', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (9, '55 Huxley Street', 'Jamaica Plain', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (10, '37587 Schiller Park', 'South End', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (11, '9 Jenna Lane', 'Roxbury', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (12, '06 Brown Plaza', 'Back Bay', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (13, '0 Grasskamp Center', 'Roxbury', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (14, '1 Crownhardt Center', 'Other', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (15, '15 Carberry Street', 'Jamaica Plain', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (16, '8 Daystar Center', 'Back Bay', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (17, '33 Arkansas Place', 'Other', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (18, '633 Stuart Hill', 'Back Bay', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (19, '74137 Killdeer Crossing', 'Allston', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (20, '3625 Schurz Trail', 'Back Bay', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (21, '44 Washington Avenue', 'Other', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (22, '764 Hoffman Junction', 'South End', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (23, '91 Victoria Hill', 'South End', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (24, '6 Graceland Park', 'Other', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (25, '563 Ridge Oak Junction', 'Jamaica Plain', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (26, '16999 Redwing Place', 'Allston', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (27, '7321 American Ash Court', 'Other', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (28, '42 Rowland Circle', 'South End', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (29, '3 Bowman Lane', 'Jamaica Plain', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (30, '9 Continental Road', 'Other', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (31, '005 Warbler Trail', 'Allston', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (32, '24 Moose Hill', 'Jamaica Plain', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (33, '1 American Junction', 'South End', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (34, '42 Mallory Court', 'Back Bay', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (35, '881 Cascade Crossing', 'Other', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (36, '57577 Scofield Pass', 'Other', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (37, '68 Bashford Plaza', 'Jamaica Plain', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (38, '38670 Milwaukee Way', 'Back Bay', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (39, '31895 Homewood Circle', 'Roxbury', 5);
INSERT INTO Location (location_id, street_name, neighborhood_name, zip_code) VALUES (40, '899 Welch Pass', 'Other', 5);
