USE bostonability;

INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (1, 1, 'Open', 'https://example.com/report_1.jpg', 1);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (2, 2, 'In Progress', 'https://example.com/report_2.jpg', 2);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (3, 3, 'Resolved', 'https://example.com/report_3.jpg', 3);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (4, 4, 'Closed', 'https://example.com/report_4.jpg', 4);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (5, 1, 'Open', 'https://example.com/report_5.jpg', 5);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (6, 2, 'In Progress', 'https://example.com/report_6.jpg', 6);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (7, 3, 'Resolved', 'https://example.com/report_7.jpg', 7);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (8, 4, 'Closed', 'https://example.com/report_8.jpg', 8);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (9, 1, 'Open', 'https://example.com/report_9.jpg', 9);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (10, 2, 'In Progress', 'https://example.com/report_10.jpg', 10);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (11, 3, 'Resolved', 'https://example.com/report_11.jpg', 11);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (12, 4, 'Closed', 'https://example.com/report_12.jpg', 12);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (13, 1, 'Open', 'https://example.com/report_13.jpg', 13);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (14, 2, 'In Progress', 'https://example.com/report_14.jpg', 14);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (15, 3, 'Resolved', 'https://example.com/report_15.jpg', 15);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (16, 4, 'Closed', 'https://example.com/report_16.jpg', 16);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (17, 1, 'Open', 'https://example.com/report_17.jpg', 17);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (18, 2, 'In Progress', 'https://example.com/report_18.jpg', 18);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (19, 3, 'Resolved', 'https://example.com/report_19.jpg', 19);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (20, 4, 'Closed', 'https://example.com/report_20.jpg', 20);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (21, 1, 'Open', 'https://example.com/report_21.jpg', 21);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (22, 2, 'In Progress', 'https://example.com/report_22.jpg', 22);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (23, 3, 'Resolved', 'https://example.com/report_23.jpg', 23);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (24, 4, 'Closed', 'https://example.com/report_24.jpg', 24);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (25, 1, 'Open', 'https://example.com/report_25.jpg', 25);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (26, 2, 'In Progress', 'https://example.com/report_26.jpg', 26);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (27, 3, 'Resolved', 'https://example.com/report_27.jpg', 27);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (28, 4, 'Closed', 'https://example.com/report_28.jpg', 28);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (29, 1, 'Open', 'https://example.com/report_29.jpg', 29);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (30, 2, 'In Progress', 'https://example.com/report_30.jpg', 30);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (31, 3, 'Resolved', 'https://example.com/report_31.jpg', 31);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (32, 4, 'Closed', 'https://example.com/report_32.jpg', 32);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (33, 1, 'Open', 'https://example.com/report_33.jpg', 33);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (34, 2, 'In Progress', 'https://example.com/report_34.jpg', 34);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (35, 3, 'Resolved', 'https://example.com/report_35.jpg', 35);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (36, 4, 'Closed', 'https://example.com/report_36.jpg', 36);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (37, 1, 'Open', 'https://example.com/report_37.jpg', 37);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (38, 2, 'In Progress', 'https://example.com/report_38.jpg', 38);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (39, 3, 'Resolved', 'https://example.com/report_39.jpg', 39);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (40, 4, 'Closed', 'https://example.com/report_40.jpg', 40);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (41, 1, 'Open', 'https://example.com/report_41.jpg', 1);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (42, 2, 'In Progress', 'https://example.com/report_42.jpg', 2);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (43, 3, 'Resolved', 'https://example.com/report_43.jpg', 3);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (44, 4, 'Closed', 'https://example.com/report_44.jpg', 4);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (45, 1, 'Open', 'https://example.com/report_45.jpg', 5);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (46, 2, 'In Progress', 'https://example.com/report_46.jpg', 6);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (47, 3, 'Resolved', 'https://example.com/report_47.jpg', 7);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (48, 4, 'Closed', 'https://example.com/report_48.jpg', 8);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (49, 1, 'Open', 'https://example.com/report_49.jpg', 9);
INSERT INTO accessibility_report (report_id, issue_type_id, report_status, photo_url, user_id) VALUES (50, 2, 'In Progress', 'https://example.com/report_50.jpg', 10);